### ISSUE TITLE
Question: is it correct that the `cv-score` functionality is broken?

### ISSUE THREAD

**Issue by pberkes** [ASPP/grader#12]
Should it work at all? It's in the `grader.conf` file but it does not seem to be connected.

For example, doing `grade cv` gives this traceback:
```
grader> grade cv
Doing grading for identity 0
Press ^C or ^D to stop
programming error: 'cv_score-0'
Traceback (most recent call last):
  File "/Users/pberkes/o/pyschool/grader/grader/grader.py", line 1287, in main
    cmd.cmdloop()
  File "/Users/pberkes/miniconda3/envs/gnode/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/pberkes/miniconda3/envs/gnode/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/pberkes/o/pyschool/grader/grader/grader.py", line 502, in do_grade
    todo = [p for p in applications
  File "/Users/pberkes/o/pyschool/grader/grader/grader.py", line 503, in <listcomp>
    if self._get_grading(p, opts.what) is None]
  File "/Users/pberkes/o/pyschool/grader/grader/grader.py", line 584, in _get_grading
    section = self.config[section_name(what, identity)]
  File "/Users/pberkes/o/pyschool/grader/grader/configfile.py", line 83, in __getitem__
    return self.sections[section]
KeyError: 'cv_score-0'
```

**Comment by keszybz** [comment]
We stopped grading CVs a while back (not sure when the last time was, maybe it wasn't ever done in the era of grader), so this probably bitrotted.
