### ISSUE TITLE
Exception raised with `stat --edition all -d`

### ISSUE THREAD

**Issue by pberkes** [ASPP/grader#7]
This is the traceback:
```
[...]
--
APPLIED
No                       =  1216 (74.0%)
Yes                      =   247 (15.0%)
0                        =    84 ( 5.1%)
NOT AVAILABLE            =    76 ( 4.6%)
1                        =    16 ( 1.0%)
                         =     4 ( 0.2%)
N/A                      =     1 ( 0.1%)
--
NAPPLIED
programming error: unorderable types: str() < int()
Traceback (most recent call last):
  File "./grader", line 1308, in main
    cmd.cmdloop()
  File "/Users/pberkes/miniconda3/envs/gnode/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/pberkes/miniconda3/envs/gnode/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "./grader", line 870, in do_stat
    self._compute_and_print_stats(pool, opts.detailed)
  File "./grader", line 901, in _compute_and_print_stats
    key=operator.itemgetter(0)):
TypeError: unorderable types: str() < int()
```

**Comment by pberkes** [comment]
🤔  I'm not getting this error any longer
Can anyone confirm?

**Comment by keszybz** [comment]
Doesn't reproduce here.

**Comment by pberkes** [comment]
Closing, then
